// Regenerates src/main/db/embeddedMigrations.ts from the .sql files in
// src/main/db/migrations/ so the embedded copy (used by production Electron
// builds and the MCP server, which don't ship the .sql files) can never drift
// from the source SQL. Run: node scripts/generateEmbeddedMigrations.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, '..');
const migrationsDir = path.join(root, 'src', 'main', 'db', 'migrations');
const outFile = path.join(root, 'src', 'main', 'db', 'embeddedMigrations.ts');

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();

const entries = files.map((file) => {
  const version = Number.parseInt(file.slice(0, file.indexOf('_')), 10);
  if (!Number.isInteger(version)) {
    throw new Error(`Migration file ${file} must start with a numeric version, e.g. 003_x.sql`);
  }
  const sql = readFileSync(path.join(migrationsDir, file), 'utf8');
  return { version, name: file, sql };
});

const header = `// AUTO-GENERATED by scripts/generateEmbeddedMigrations.mjs from
// src/main/db/migrations/*.sql. DO NOT EDIT BY HAND. Regenerate after changing
// any migration SQL: node scripts/generateEmbeddedMigrations.mjs
`;

const body = `export const EMBEDDED_MIGRATIONS = ${JSON.stringify(entries, null, 2)} as const;\n`;

writeFileSync(outFile, header + body, 'utf8');
console.log(`Wrote ${entries.length} migration(s) to ${path.relative(root, outFile)}:`);
for (const e of entries) {
  console.log(`  v${e.version}  ${e.name}  (${e.sql.length} bytes)`);
}
